language: javascript
dist: xenial
dotnet: 3.1

install: 
- bash ./cicd.sh install

script:
- bash ./cicd.sh build

deploy:
  provider: script
  script: bash ./cicd.sh deploy
  on:
    branch: release
    tags: true
